"""goal_requires_account

Revision ID: 06dd7a568f0e
Revises: 6b38305e6931
Create Date: 2026-06-12 12:47:41.096417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06dd7a568f0e'
down_revision: Union[str, Sequence[str], None] = '6b38305e6931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
