"""account_snapshot

Revision ID: 477f75453efb
Revises: cba77114334e
Create Date: 2026-06-05 01:35:52.319534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '477f75453efb'
down_revision: Union[str, Sequence[str], None] = 'cba77114334e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_snapshot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_snapshot',
    sa.Column('snapshot_id', sa.INTEGER(), nullable=False),
    sa.Column('account_id', sa.INTEGER(), nullable=False),
    sa.Column('balance', sa.NUMERIC(), nullable=False),
    sa.Column('captured_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    # ### end Alembic commands ###
