"""initial_schema

Revision ID: 6b38305e6931
Revises: 
Create Date: 2026-06-12 08:26:23.339896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b38305e6931'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('decimal_places', sa.Integer(), nullable=False),
    sa.CheckConstraint('decimal_places >= 0', name='ck_currency_decimal_places'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('account',
    sa.Column('account_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint("status IN ('active','archived')", name='ck_account_status'),
    sa.ForeignKeyConstraint(['currency_code'], ['currency.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index('ix_account_currency_code', 'account', ['currency_code'], unique=False)
    op.create_index('ix_account_user_id', 'account', ['user_id'], unique=False)
    op.create_table('budget',
    sa.Column('budget_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.CheckConstraint("period IN ('weekly','monthly','quarterly','yearly','custom')", name='ck_budget_period'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('budget_id')
    )
    op.create_index('ix_budget_start_date', 'budget', ['start_date'], unique=False)
    op.create_index('ix_budget_user_id', 'budget', ['user_id'], unique=False)
    op.create_table('category_group',
    sa.Column('group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.CheckConstraint("type IN ('income','expense')", name='ck_category_group_type'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_index('ix_category_group_user_id', 'category_group', ['user_id'], unique=False)
    op.create_table('tag',
    sa.Column('tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_index('ix_tag_user_id', 'tag', ['user_id'], unique=False)
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['category_group.group_id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index('ix_category_group_id', 'category', ['group_id'], unique=False)
    op.create_index('ix_category_is_active', 'category', ['is_active'], unique=False)
    op.create_table('goal',
    sa.Column('goal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_amount_minor', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint("status IN ('active','completed')", name='ck_goal_status'),
    sa.CheckConstraint('target_amount_minor > 0', name='ck_goal_target_amount_minor'),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.create_index('ix_goal_account_id', 'goal', ['account_id'], unique=False)
    op.create_index('ix_goal_user_id', 'goal', ['user_id'], unique=False)
    op.create_table('budget_item',
    sa.Column('budget_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('planned_amount_minor', sa.Integer(), nullable=False),
    sa.Column('rollover_enabled', sa.Boolean(), nullable=False),
    sa.CheckConstraint('planned_amount_minor >= 0', name='ck_budget_item_planned_amount_minor'),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.budget_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.PrimaryKeyConstraint('budget_item_id')
    )
    op.create_index('ix_budget_item_budget_id', 'budget_item', ['budget_id'], unique=False)
    op.create_index('ix_budget_item_category_id', 'budget_item', ['category_id'], unique=False)
    op.create_table('recurring',
    sa.Column('recurring_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('merchant', sa.String(), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('frequency_unit', sa.String(), nullable=False),
    sa.Column('next_due', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint("frequency_unit IN ('day','week','month','year')", name='ck_recurring_frequency_unit'),
    sa.CheckConstraint("status IN ('active','paused','inactive')", name='ck_recurring_status'),
    sa.CheckConstraint('amount_minor <> 0', name='ck_recurring_amount_minor'),
    sa.CheckConstraint('interval > 0', name='ck_recurring_interval'),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.PrimaryKeyConstraint('recurring_id')
    )
    op.create_index('ix_recurring_account_id', 'recurring', ['account_id'], unique=False)
    op.create_index('ix_recurring_category_id', 'recurring', ['category_id'], unique=False)
    op.create_index('ix_recurring_next_due', 'recurring', ['next_due'], unique=False)
    op.create_index('ix_recurring_status', 'recurring', ['status'], unique=False)
    op.create_table('transaction',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('recurring_id', sa.Integer(), nullable=True),
    sa.Column('transfer_pair_id', sa.Integer(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('merchant', sa.String(), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('txn_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending','cleared','void')", name='ck_transaction_status'),
    sa.CheckConstraint('amount_minor <> 0', name='ck_transaction_amount_minor'),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.goal_id'], ),
    sa.ForeignKeyConstraint(['recurring_id'], ['recurring.recurring_id'], ),
    sa.ForeignKeyConstraint(['transfer_pair_id'], ['transaction.transaction_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index('ix_transaction_account_id', 'transaction', ['account_id'], unique=False)
    op.create_index('ix_transaction_category_id', 'transaction', ['category_id'], unique=False)
    op.create_index('ix_transaction_goal_id', 'transaction', ['goal_id'], unique=False)
    op.create_index('ix_transaction_recurring_id', 'transaction', ['recurring_id'], unique=False)
    op.create_index('ix_transaction_status', 'transaction', ['status'], unique=False)
    op.create_index('ix_transaction_txn_date', 'transaction', ['txn_date'], unique=False)
    op.create_table('transaction_tag',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.transaction_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id', 'tag_id')
    )
    op.create_index('ix_transaction_tag_tag_id', 'transaction_tag', ['tag_id'], unique=False)
    op.create_index('ix_transaction_tag_transaction_id', 'transaction_tag', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_tag_transaction_id', table_name='transaction_tag')
    op.drop_index('ix_transaction_tag_tag_id', table_name='transaction_tag')
    op.drop_table('transaction_tag')
    op.drop_index('ix_transaction_txn_date', table_name='transaction')
    op.drop_index('ix_transaction_status', table_name='transaction')
    op.drop_index('ix_transaction_recurring_id', table_name='transaction')
    op.drop_index('ix_transaction_goal_id', table_name='transaction')
    op.drop_index('ix_transaction_category_id', table_name='transaction')
    op.drop_index('ix_transaction_account_id', table_name='transaction')
    op.drop_table('transaction')
    op.drop_index('ix_recurring_status', table_name='recurring')
    op.drop_index('ix_recurring_next_due', table_name='recurring')
    op.drop_index('ix_recurring_category_id', table_name='recurring')
    op.drop_index('ix_recurring_account_id', table_name='recurring')
    op.drop_table('recurring')
    op.drop_index('ix_budget_item_category_id', table_name='budget_item')
    op.drop_index('ix_budget_item_budget_id', table_name='budget_item')
    op.drop_table('budget_item')
    op.drop_index('ix_goal_user_id', table_name='goal')
    op.drop_index('ix_goal_account_id', table_name='goal')
    op.drop_table('goal')
    op.drop_index('ix_category_is_active', table_name='category')
    op.drop_index('ix_category_group_id', table_name='category')
    op.drop_table('category')
    op.drop_index('ix_tag_user_id', table_name='tag')
    op.drop_table('tag')
    op.drop_index('ix_category_group_user_id', table_name='category_group')
    op.drop_table('category_group')
    op.drop_index('ix_budget_user_id', table_name='budget')
    op.drop_index('ix_budget_start_date', table_name='budget')
    op.drop_table('budget')
    op.drop_index('ix_account_user_id', table_name='account')
    op.drop_index('ix_account_currency_code', table_name='account')
    op.drop_table('account')
    op.drop_table('user')
    op.drop_table('currency')
    # ### end Alembic commands ###
