"""initial schema

Revision ID: 756f5c520879
Revises: 
Create Date: 2026-06-23 11:11:31.927452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '756f5c520879'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('account',
    sa.Column('account_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('opening_balance_minor', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'active'"), nullable=False),
    sa.CheckConstraint("status IN ('active','archived')", name='ck_account_status'),
    sa.CheckConstraint("type IN ('checking','savings','cash','credit_card','line_of_credit','loan','mortgage','investment','other_asset','other_liability')", name='ck_account_type'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_account_user_name')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index('ix_account_status', ['status'], unique=False)
        batch_op.create_index('ix_account_user_id', ['user_id'], unique=False)

    op.create_table('budget',
    sa.Column('budget_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('period_type', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("period_type IN ('weekly','monthly','quarterly','yearly','custom')", name='ck_budget_period_type'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('budget_id'),
    sa.UniqueConstraint('user_id', 'name', 'start_date', name='uq_budget_user_name_start_date')
    )
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.create_index('ix_budget_period_type', ['period_type'], unique=False)
        batch_op.create_index('ix_budget_start_date', ['start_date'], unique=False)
        batch_op.create_index('ix_budget_user_id', ['user_id'], unique=False)

    op.create_table('category_group',
    sa.Column('group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("type IN ('income','expense','transfer')", name='ck_category_group_type'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('user_id', 'type', 'name', name='uq_category_group_user_type_name')
    )
    with op.batch_alter_table('category_group', schema=None) as batch_op:
        batch_op.create_index('ix_category_group_is_active', ['is_active'], unique=False)
        batch_op.create_index('ix_category_group_type', ['type'], unique=False)
        batch_op.create_index('ix_category_group_user_id', ['user_id'], unique=False)

    op.create_table('goal',
    sa.Column('goal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_amount_minor', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'active'"), nullable=False),
    sa.CheckConstraint("status IN ('active','completed')", name='ck_goal_status'),
    sa.CheckConstraint('target_amount_minor > 0', name='ck_goal_target_amount_minor'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('goal_id')
    )
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.create_index('ix_goal_status', ['status'], unique=False)
        batch_op.create_index('ix_goal_user_id', ['user_id'], unique=False)

    op.create_table('tag',
    sa.Column('tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_tag_user_name')
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index('ix_tag_user_id', ['user_id'], unique=False)

    op.create_table('category',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['category_group.group_id'], ),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('group_id', 'name', name='uq_category_group_name')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index('ix_category_group_id', ['group_id'], unique=False)
        batch_op.create_index('ix_category_is_active', ['is_active'], unique=False)

    op.create_table('goal_account',
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('allocated_amount_minor', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('allocated_amount_minor >= 0', name='ck_goal_account_allocated_amount_minor'),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.goal_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('goal_id', 'account_id')
    )
    with op.batch_alter_table('goal_account', schema=None) as batch_op:
        batch_op.create_index('ix_goal_account_account_id', ['account_id'], unique=False)
        batch_op.create_index('ix_goal_account_goal_id', ['goal_id'], unique=False)

    op.create_table('budget_item',
    sa.Column('budget_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('planned_amount_minor', sa.Integer(), nullable=False),
    sa.Column('rollover_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('planned_amount_minor >= 0', name='ck_budget_item_planned_amount_minor'),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.budget_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.PrimaryKeyConstraint('budget_item_id'),
    sa.UniqueConstraint('budget_id', 'category_id', name='uq_budget_item_budget_category')
    )
    with op.batch_alter_table('budget_item', schema=None) as batch_op:
        batch_op.create_index('ix_budget_item_budget_id', ['budget_id'], unique=False)
        batch_op.create_index('ix_budget_item_category_id', ['category_id'], unique=False)

    op.create_table('recurring_rule',
    sa.Column('recurring_rule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('expected_amount_minor', sa.Integer(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('frequency_unit', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('next_due_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'active'"), nullable=False),
    sa.CheckConstraint("frequency_unit IN ('day','week','month','year')", name='ck_recurring_rule_frequency_unit'),
    sa.CheckConstraint("status IN ('active','paused','inactive')", name='ck_recurring_rule_status'),
    sa.CheckConstraint('expected_amount_minor <> 0', name='ck_recurring_rule_expected_amount_minor'),
    sa.CheckConstraint('interval > 0', name='ck_recurring_rule_interval'),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.PrimaryKeyConstraint('recurring_rule_id')
    )
    with op.batch_alter_table('recurring_rule', schema=None) as batch_op:
        batch_op.create_index('ix_recurring_rule_account_id', ['account_id'], unique=False)
        batch_op.create_index('ix_recurring_rule_category_id', ['category_id'], unique=False)
        batch_op.create_index('ix_recurring_rule_next_due_date', ['next_due_date'], unique=False)
        batch_op.create_index('ix_recurring_rule_status', ['status'], unique=False)

    op.create_table('transaction',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('budget_item_id', sa.Integer(), nullable=True),
    sa.Column('recurring_rule_id', sa.Integer(), nullable=True),
    sa.Column('payee', sa.String(), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('amount_minor <> 0', name='ck_transaction_amount_minor'),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.ForeignKeyConstraint(['budget_item_id'], ['budget_item.budget_item_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['recurring_rule_id'], ['recurring_rule.recurring_rule_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index('ix_transaction_account_id', ['account_id'], unique=False)
        batch_op.create_index('ix_transaction_budget_item_id', ['budget_item_id'], unique=False)
        batch_op.create_index('ix_transaction_category_id', ['category_id'], unique=False)
        batch_op.create_index('ix_transaction_recurring_rule_id', ['recurring_rule_id'], unique=False)
        batch_op.create_index('ix_transaction_transaction_date', ['transaction_date'], unique=False)
        batch_op.create_index('ix_transaction_transfer_id', ['transfer_id'], unique=False)

    op.create_table('transaction_tag',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.transaction_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id', 'tag_id')
    )
    with op.batch_alter_table('transaction_tag', schema=None) as batch_op:
        batch_op.create_index('ix_transaction_tag_tag_id', ['tag_id'], unique=False)
        batch_op.create_index('ix_transaction_tag_transaction_id', ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_tag', schema=None) as batch_op:
        batch_op.drop_index('ix_transaction_tag_transaction_id')
        batch_op.drop_index('ix_transaction_tag_tag_id')

    op.drop_table('transaction_tag')
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index('ix_transaction_transfer_id')
        batch_op.drop_index('ix_transaction_transaction_date')
        batch_op.drop_index('ix_transaction_recurring_rule_id')
        batch_op.drop_index('ix_transaction_category_id')
        batch_op.drop_index('ix_transaction_budget_item_id')
        batch_op.drop_index('ix_transaction_account_id')

    op.drop_table('transaction')
    with op.batch_alter_table('recurring_rule', schema=None) as batch_op:
        batch_op.drop_index('ix_recurring_rule_status')
        batch_op.drop_index('ix_recurring_rule_next_due_date')
        batch_op.drop_index('ix_recurring_rule_category_id')
        batch_op.drop_index('ix_recurring_rule_account_id')

    op.drop_table('recurring_rule')
    with op.batch_alter_table('budget_item', schema=None) as batch_op:
        batch_op.drop_index('ix_budget_item_category_id')
        batch_op.drop_index('ix_budget_item_budget_id')

    op.drop_table('budget_item')
    with op.batch_alter_table('goal_account', schema=None) as batch_op:
        batch_op.drop_index('ix_goal_account_goal_id')
        batch_op.drop_index('ix_goal_account_account_id')

    op.drop_table('goal_account')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index('ix_category_is_active')
        batch_op.drop_index('ix_category_group_id')

    op.drop_table('category')
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index('ix_tag_user_id')

    op.drop_table('tag')
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_index('ix_goal_user_id')
        batch_op.drop_index('ix_goal_status')

    op.drop_table('goal')
    with op.batch_alter_table('category_group', schema=None) as batch_op:
        batch_op.drop_index('ix_category_group_user_id')
        batch_op.drop_index('ix_category_group_type')
        batch_op.drop_index('ix_category_group_is_active')

    op.drop_table('category_group')
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_index('ix_budget_user_id')
        batch_op.drop_index('ix_budget_start_date')
        batch_op.drop_index('ix_budget_period_type')

    op.drop_table('budget')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index('ix_account_user_id')
        batch_op.drop_index('ix_account_status')

    op.drop_table('account')
    op.drop_table('user')
    # ### end Alembic commands ###
